### ISSUE TITLE
[Request/Suggestion] Support unpredictable frame drops and unmatching speed/pitch (drift correction)

### ISSUE THREAD

**Issue by alopatindev** [protyposis/AudioAlign#12]
If anyone considers implementing [this feature](https://github.com/benfmiller/audalign/issues/54) in AudioAlign/Aurio and/or suggests possible ideas for implementation, please share them here. Thanks!

**Comment by protyposis** [comment]
What you are describing is generally referred to as drift correction. Drift is usually, but not necessarily always, related to pitch change.

> unpredictable frame drops in both tracks

This can be interpreted as a case of non-linear drift (w/o pitch change).

> unmatching overall average speed (often with higher pitch for faster audio)

This can be interpreted as linear drift, which is the simplest case (e.g., PAL speed-up).

AudioAlign already includes tools to handle drift semi-automatically, but I'll need to validate. Could you provide example files?

**Comment by alopatindev** [comment]
> Could you provide example files?

Sure, here are [some examples](http://45.88.77.178/data.7z) of problematic extracted audio tracks (password is `SyncWithDriftCorrection`, size is `≈11 GiB`, sha256sum is `dff403ac3d1958eff2636b3806af8a58cc21a37bb64e36dae2cef5e7813fbaf2`).

Please note that some of these files may contain multiple audio tracks, sometimes with wrong language labels. Thanks!

**Comment by protyposis** [comment]
Thanks, here's an example video with the `The_OC` set. I'm not sure what dubbed vs. restored means, but I used the `dubbed_1` and `restored` files as they seem to be two different languages with a different runtime. I transcoded them to .wav because direct FFmpeg decoding in AudioAlign isn't super stable yet. The aligned tracks are perfectly in sync:

https://github.com/protyposis/AudioAlign/assets/189372/e619fd13-3486-43f5-83dd-eb2de671e7e0

Looking at the alignment graph, we can immediately see that there's
- linear drift (diagonal line instead of horizontal)
- a few obvious "frame drops" seen as glitches in the diagonal line (circled in red):

![image](https://github.com/protyposis/AudioAlign/assets/189372/93ee0710-4101-4e2f-8cf5-3c3dc06dfa48)

**Comment by alopatindev** [comment]
Wow, thanks for checking it; that's really great that AudioAlign can handle such cases!

**Comment by andonagio** [comment]
This is awesome. Is it possible to achieve this via command line? I have a batch of files with frame rate/pitch issues that need to be synced up, and I'd rather not do each one manually.

**Comment by darkvertex** [comment]
Me too I'm curious if there's a possibility of a commandline to maybe do default alignment with the default algorithm and to sync to the first match and export an xml.
