### ISSUE TITLE
How to run experiments on Aurio or AudioAlign?

### ISSUE THREAD

**Issue by KassemKallas** [protyposis/AudioAlign#2]
Hi,

I am a researcher and I need to perform some experiments on Aurio to compare to some state of the art audio/video identification techniques. Still I am stacked on the steps to follow in order to run the experiments. Which software to be used, Aurio or AudioAlign? and how? still Audio Algin is giving me errors when I run the downloaded version. Please, can you help me with this?

Thank you

**Comment by protyposis** [comment]
Hi! As the description says, AudioAlign is basically a graphical user interface that uses Aurio to provide certain functionality. If you want to develop some custom software on your own, you'd use Aurio. Since you're asking this question I assume you're not familiar with software development so I'd say your tool of choice is AudioAlign. Would be helpful to know which experiments you want to run though :)

Regarding the errors, please post them here so I can take a look.

**Comment by KassemKallas** [comment]
In fact, work with software development but mainly for signal processing for security application as we for our research discipline so most of the time i use Matlab. I am not an expert at all with .net. Yes I would like to explain me please how can run expriment usibg Aurio.

**Comment by protyposis** [comment]
To be able to help you, I need to know which experiments you want to run, how you're trying to run them and what the errors are that you're getting.
