### ISSUE TITLE
Failed dynamic resampling

### ISSUE THREAD

**Issue by viric** [protyposis/AudioAlign#4]
Hello,

I have two recording devices for the same scene (a conference), with slightly different different clock. I wanted to try the dynamic resampling with all matches, and it crashed (TimeWarpCollection.cs:94 (ValidateMappings()). Invalid sample ratio: NaN.

To make it work, I updated the ffmpeg proxy a bit to use ffmpeg 3.1. I cannot find 2.8 binaries anywhere and some API functions have been deprecated.

**Comment by protyposis** [comment]
That's probably because you're using *all* matches, and if they overlap in some way this leads to such errors. It is a known issue.

To solve it, filter the matches before aligning the tracks. In "Match & Align" > "Alignment", select
 * Mode "best", check "windowed"
 * Window size can be played with, but the default (30secs) should be good for recordings > 5 minutes
 * keep "remove unused matching points" checked as by default
and hit "Filter Matches". Now they should be cleaned from overlaps and "Align Tracks" should work.

Would you be willing to open a PR for the FFmpeg upgrade?

**Comment by protyposis** [comment]
The newest version validates the matches before executing the alignment and would detect this problem in advance.
